server:
  port: ${PORT:8085}
eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka
spring:
  data:
    mongodb:
      uri: mongodb://catalog-db:27018/catalog
  zipkin:
    base-url: http://zipkin:9411/
    enabled: true

  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq
    port: 5672

queue:
  serie:
    name: serieQueue
  movie:
    name: movieQueue
    
resilience4j:
  circuitbreaker:
    instances:
      getCatalog:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
    instances:
      getCatalog:
        maxAttempts: 3
        waitDuration: 1000
        retryExceptions[0]: feign.FeignException$InternalServerError
management:
  endpoint:
    health:
      show-details: always
    web:
      exposure:
        include: circuitbreakers, circuitbreakersevents, health, info, ratelimiters, metrics
  health:
    circuitbreakers:
      enabled: true