server:
  port: ${PORT:8083}
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    service-url:
      defaultZone: http://service-registry:8761/eureka
    
spring:
  data:
    mongodb:
      uri: mongodb://series-db:27017/series
  zipkin:
    base-url: http://zipkin:9411/
    enabled: true

  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq
    port: 5672

queue:
  serie:
    name: serieQueue